src/apps/login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = "login"


urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name="login/login.html"), name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

src/apps/plots/urls.py
from django.urls import path

from . import views, api


app_name = "plots"


urlpatterns = [
    # Views:
    path('', views.show, name="show"),
    path('insert', views.insert, name="insert"),

    # API:
    path('get_country_data', api.get_country_data, name="get_country_data"),
]

src/covid/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings, views


urlpatterns = [
    # Admin view:
    path('admin/', admin.site.urls),

    # User stuff:
    path('user/', views.user, name="user"),

    # Main:
    path('', views.main_index, name="main_index"),
]

# Apps:
for app in settings.EXTRA_APPS:
    app_name = app.split(".")[-1]  # if app = "apps.app_name", "fix" it
    urlpatterns.append(path(f'{app_name}/', include(f'{app}.urls', namespace=app_name)))

src/apps/plots/models.py
from django.db import models


class Country(models.Model):
    name = models.CharField('Name', max_length=50)
    iso = models.CharField('ISO code', max_length=6, default="xxx")
    tag = models.CharField('Tag', max_length=50)
    line_color = models.CharField('Color', max_length=8, default="#000000")

    def __str__(self):
        return self.name

    def __lt__(self, other):
        return self.name < other.name


class DataPoint(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    date = models.DateField("Date")
    cases = models.IntegerField("Cases", default=0)
    deaths = models.IntegerField("Deaths", default=0)
    recoveries = models.IntegerField("Recoveries", default=0)

    def __str__(self):
        return f"{self.date}: {self.country}"

src/apps/login/forms.py
from django import forms
from django.contrib.auth.models import User


class MyUserCreationForm(forms.Form):
    username = forms.CharField(
        label="User name",
        help_text="No spaces and lowercase",
    )
    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput,
        help_text=None,
    )
    password2 = forms.CharField(
        label="Repeat password",
        widget=forms.PasswordInput,
        strip=False,
        help_text="Re-introduce the same password, to verify it.",
    )
    email = forms.EmailField(label="e-mail")

    def is_valid(self):
        """Perform default validation, plus some extra custom ones (such as matching passwords)."""

        # Fail if default check fails:
        if not super(forms.Form, self).is_valid():
            return False

        # Fail if empty password or confirmation does not match:
        pw1 = self.cleaned_data["password1"]
        pw2 = self.cleaned_data["password2"]

        if pw1 != pw2:
            self.add_error('password2', "Passwords do not coincide.")
            return False

        # Fail if username or e-mail already taken:
        if User.objects.filter(username=self.cleaned_data["username"]).exists():
            self.add_error('username', "User name already exists.")
            return False

        if User.objects.filter(email=self.cleaned_data["email"]).exists():
            self.add_error('email', "User with that e-mail address already exists.")
            return False

        return True

    def save(self):
        """
        Save a user with info in this form.
        Return created user.
        """
        data = self.cleaned_data
        new_user = User(
            username=data["username"],
            email=data["email"],
        )
        new_user.set_password(data["password1"])
        new_user.save()

        return new_user

src/apps/plots/forms.py
from django import forms

from .models import Country, DataPoint


class CountryForm(forms.ModelForm):

    class Meta:
        model = Country
        fields = ["name"]

    def save(self):
        data = self.cleaned_data

        # Avoid duplicates:
        if Country.objects.filter(name=data["name"]).exists():
            return

        country = Country()
        country.name = data["name"]
        country.tag = data["name"].replace(" ", "_").lower()
        country.save()


class DataPointForm(forms.ModelForm):

    class Meta:
        model = DataPoint
        widgets = {
            "date": forms.DateInput(format="%Y-%m-%d"),
        }
        fields = ["country", "date", "cases", "deaths", "recoveries"]

    def save(self):
        data = self.cleaned_data
        data_point = DataPoint()
        data_point.country = data["country"]
        data_point.date = data["date"]
        data_point.cases = data["cases"]
        data_point.deaths = data["deaths"]
        data_point.recoveries = data["recoveries"]
        data_point.save()

src/apps/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as auth_logout, login

from .forms import MyUserCreationForm


def logout(request):
    """Log out user (if logged in)."""

    auth_logout(request)

    return redirect('main_index')


def signup(request):
    """Register a user."""

    if request.method == "POST":
        form = MyUserCreationForm(request.POST)
        if not form.is_valid():
            context = {
                "form": form,
            }
            return render(request, "login/signup.html", context)

        # Save new user in DB:
        new_user = form.save()

        # Log-in as newly-created user:
        login(request, user=new_user)

        return redirect("main_index")
    else:
        form = MyUserCreationForm()

        context = {
            "form": form,
        }

        return render(request, "login/signup.html", context)

src/apps/plots/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from . import core
from .models import Country
from .forms import CountryForm, DataPointForm
from .handle_views.get.insert import handle_insert_get
from .handle_views.post.insert import handle_insert_post


@login_required
def insert(request):
    if request.method != "POST":
        return handle_insert_get(request)

    if request.POST.get("country_form") is not None:
        return handle_insert_post(request, CountryForm)

    if request.POST.get("datapoint_form") is not None:
        return handle_insert_post(request, DataPointForm)

    return handle_insert_get(request)


@login_required
def show(request):
    context = {
        "show_active": True,
        "cases_plot": core.get_progress_plot_div(),
        "countries": Country.objects.order_by("name"),
    }

    return render(request, "plots/show.html", context)

src/covid/views.py
from django.shortcuts import render, redirect


def user(request):
    return render(request, "user.html", {})


def main_index(request):
    if request.user.is_authenticated:
        return redirect('plots:show')
    else:
        return redirect('login:login')

src/apps/login/templates/login/base_login.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"
            integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore.js"></script>

    {% block extra_head %}
    {% endblock %}

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h3 class="my-0 mr-md-auto font-weight-normal">
            {% block section_name %}
            {% endblock %}
        </h3>
        <div class="mr-auto">
            {% block status %}
            {% endblock %}
        </div>

        {% block top_menu %}
        {% endblock %}
    </div>

    <div style="width: 90%; margin-left: 5%;">
        {% block body %}
        {% endblock %}
    </div>
 </body>

src/apps/login/templates/login/login.html
{% extends "login/base_login.html" %}
{% load login_filters %}

{% block section_name %}
Log in
{% endblock %}

{% block body %}
{% if form.errors %}
<p>Incorrect user name and/or password. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="POST" action="{% url 'login:login' %}">
    {% csrf_token %}
    <div class="input-group mt-3">
        <div class="input-group-prepend ml-0 col-2">
            <label class="input-group-text w-100">User name:</label>
        </div>
        {{ form.username|add_class:'form-control form-control-lg col-1' }}
    </div>

    <div class="input-group mt-3">
        <div class="input-group-prepend ml-0 col-2">
            <label class="input-group-text w-100">Password:</label>
        </div>
        {{ form.password|add_class:'form-control form-control-lg col-1' }}
    </div>

    <button class="btn btn-success btn-lg mt-3" type="submit">Log in</button>
    <a class="btn btn-lg mt-3 btn-warning" href="{% url 'plots:show' %}">Cancel</a>
</form>

{# Assumes you setup the password_reset view in your URL conf #}
<p>Don't have an account? <a href="{% url 'login:signup' %}">Sign up</a></p>
{% endblock %}

src/apps/login/templates/login/master_layout.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"
            integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore.js"></script>

    {% block extra_head %}
    {% endblock %}

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h3 class="my-0 mr-md-auto font-weight-normal">
            {% block section_name %}
            {% endblock %}
        </h3>
        <div class="mr-auto">
            {% block status %}
            {% endblock %}
        </div>

        {% block top_menu %}
        {% endblock %}
    </div>

    <div style="width: 90%; margin-left: 5%;">
        {% block body %}
        {% endblock %}
    </div>
 </body>

src/apps/login/templates/login/signup.html
{% extends "login/base_login.html" %}

{% block body %}

<form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="btn btn-success" type="submit">Register</button>
    <a class="btn btn-warning" href="{% url 'main_index' %}">Cancel</a>
</form>

{% endblock %}

src/apps/plots/templates/plots/base_plots.html
{% extends "base.html" %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'plots/css/plots.css' %}" />
<script src="{% static 'plots/js/plots.js' %}"></script>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

{% block top_right %}
{% include "plots/plots_menu.html" %}
{% include "covid_menu.html" %}
{% endblock %}

src/apps/plots/templates/plots/insert.html
{% extends "plots/base_plots.html" %}

{% load static %}

{% block title %}
Plots
{% endblock %}

{% block body %}
<div class="insert-grid mt-5">
    <div>
        <form method="POST">
            {% csrf_token %}
            {{datum_form}}
            <button class="btn btn-success ml-1" name="datapoint_form" value="true" type="submit">Add</button>
        </form>

        <div class="data-point-grid mt-4">
            <div class="data-point-header">Date</div>
            <div class="data-point-header">Country</div>
            <div class="data-point-header">Cases</div>
            <div class="data-point-header">Deaths</div>
            <div class="data-point-header">Recoveries</div>

            {% for latest in latest_data_points %}
                <div>{{latest.date}}</div>
                <div>{{latest.country}}</div>
                <div>{{latest.cases}}</div>
                <div>{{latest.deaths}}</div>
                <div>{{latest.recoveries}}</div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-5" style="justify-items: center;">
        <div class="country-list-grid">
            {% for country in countries %}
            <div>{{country}}</div>
            {% endfor %}
        </div>

        <form class="mt-4 ml-0" method="POST">
            {% csrf_token %}
            {{country_form}}
            <button class="btn btn-success ml-1" name="country_form" value="true" type="submit">Add</button>
        </form>
    </div>
</div>
{% endblock %}

src/apps/plots/templates/plots/main.html
{% extends "plots/base_plots.html" %}

{% load static %}

{% block title %}
Plots
{% endblock %}

{% block body %}
{% endblock %}

src/apps/plots/templates/plots/plots_menu.html
<div class="btn-group ml-3">
    <a class="btn {% if show_active %}btn-primary{% else %}btn-secondary{% endif %} btn-lg"
       href="{% url 'plots:show' %}">Show</a>
    <a class="btn {% if insert_active %}btn-primary{% else %}btn-secondary{% endif %} btn-lg"
       href="{% url 'plots:insert' %}">Insert</a>
</div>

src/apps/plots/templates/plots/show.html
{% extends "plots/base_plots.html" %}

{% load static %}

{% block title %}
Plots
{% endblock %}

{% block top_left %}
{% for country in countries %}
    <button class="btn btn-lg btn-success" id="id-exp-{{country.tag}}"
            onclick="toggle_country('{{country.tag}}')">{{country.name}}</button>
{% endfor %}

<div class="btn-group ml-2" id="id-which-case">
    <button class="btn btn-primary btn-lg" id="id-show-cases" onclick="show_cases()">Cases</button>
    <button class="btn btn-secondary btn-lg" id="id-show-deaths" onclick="show_deaths()">Deaths</button>
</div>
{% endblock %}

{% block body %}
<span id="country-list">
    {% for country in countries %}
    <span data-country-tag="{{country.tag}}"></span>
    {% endfor %}
</span>

<div class="mt-1 style="height: 1200px;">
    {{cases_plot|safe}}
</div>

<script>
    addLoadEvent(on_plot_view_load());
</script>
{% endblock %}

src/covid/templates/base.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Our CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    <!-- Other -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"
            integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore.js"></script>

    {% block extra_head %}
    {% endblock %}

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body>
    <div class="top-grid">
        <div>
            {% block top_left %}
            {% endblock %}
        </div>

        <div>
            {% block top_middle %}
            {% endblock %}
        </div>

        <div>
            {% block top_right %}
            {% endblock %}
        </div>
    </div>

    <div class="ml-2 mr-2">
        {% block body %}
        {% endblock %}
    </div>
 </body>

src/covid/templates/covid_menu.html
<div class="btn-group ml-3">
    <a class="btn btn-secondary btn-lg" href="/">Home</a>
    {% if user.is_authenticated %}
        <a class="btn btn-success btn-lg" href="{% url 'user' %}">{{user.username}}</a>
    {% else %}
        <a class="btn btn-danger btn-lg" href="{% url 'login' %}">Log in</a>
    {% endif %}
</div>

src/covid/templates/user.html
{% extends "base.html" %}
{% load login_filters %}

{% block section_name %}
User
{% endblock %}

{% block body %}
{% if form.errors %}
<p>An error happened. Please try again.</p>
{% endif %}

<div>
    <a class="btn btn-lg mt-3 btn-warning" href="/">Cancel</a>
    <a class="btn btn-lg mt-3 btn-danger" href="{% url 'login:logout' %}">Log out</a>
</div>
{% endblock %}